name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore NuGet Packages
      run: nuget restore Rectify11Installer.sln
    - name: Build
      run: msbuild Rectify11Installer.sln /p:Configuration=Release
